version: "3.8"

services:
  rails_app:
    image: luismwolf/article-manager-rails:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DEFAULT_PORT: 3000

  react_app:
    image: luismwolf/article-manager-react:latest
    build:
      context: ./article-manager-react
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    links:
      - "rails_app:localhost"

  html_client:
    image: luismwolf/article-manager-html:latest
    build:
      context: ./article-manager-html
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
